# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Plain Interface
#' @noRd
linesplit_from_R_plain <- function(str, sxparr) {
    .Call(`_linesplitter_linesplit_from_R_plain`, str, sxparr)
}

